name: upload artifact
on: push

jobs:
    UploadArt:
        runs-on: ubuntu-latest
        steps:
          - name: checkout branchs
            uses: action/chcekout@v2
            
          - name: upload artifact
            uses: action/upload-artifact@v2
            with:
               name: ${{ secret.ART_NAME }}
               path: .
