name: upload artifact
on: push

jobs:
    UploadArt:
        runs-on: ubuntu-latest
        steps:
          - name: checkout branchs
            uses: actions/chcekout@v2
            
          - name: upload artifact
            uses: actions/upload-artifact@v2
            with:
               name: ${{ secrets.ART_NAME }}
               path: .
