# This is a basic workflow to help you get started with Actions

name: CI
on: push
    
jobs:
  kotlinFormatter:
          runs-on: ubuntu-latest
          steps:
            - name: Kotlin Linter
              # You may pin to the exact commit or the version.
              # uses: vroy/gha-kotlin-linter@203eb96c88c48320dd3a37a7edf1e748e713f214
              uses: vroy/gha-kotlin-linter@v4
  
