name: complex
on: push

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
        - run: date
    windows:
        runs-on: windows-latest
        steps:
        - run: date
    macOs:
        runs-on: macos-latest
        steps:
        - run: date
    dependency:
        needs: [ubuntu, windows, macOS]
        runs-on: macos-latest
        steps:
        - run: date
        
